module.exports = {
  async up(queryInterface) {
    await queryInterface.bulkInsert(
      'Users',
      [
        {
          login: 11065,
          password: '11065',
          surname: 'Гнутов',
          name: 'Федор',
          patronymic: 'Александрович',
          isMale: true,
          role: 'professor',
          departmentId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 223,
          password: '223',
          surname: 'Гордеев',
          name: 'Николай',
          patronymic: 'Леонидович',
          isMale: true,
          role: 'professor',
          departmentId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 9552,
          password: '9552',
          surname: 'Егорченкова',
          name: 'Елизавета',
          patronymic: 'Алексеевна',
          isMale: false,
          role: 'professor',
          departmentId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 2122,
          password: '2122',
          surname: 'Кушпель',
          name: 'Надежда',
          patronymic: 'Николаевна',
          isMale: false,
          role: 'professor',
          departmentId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 3629,
          password: '3629',
          surname: 'Певзнер',
          name: 'Игорь',
          patronymic: 'Михайлович',
          isMale: true,
          role: 'professor',
          departmentId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 1029,
          password: '1029',
          surname: 'Хамов',
          name: 'Геннадий',
          patronymic: 'Григорьевич',
          isMale: true,
          role: 'professor',
          departmentId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 1127,
          password: '1127',
          surname: 'Яшина',
          name: 'Елена',
          patronymic: 'Юрьевна',
          isMale: false,
          role: 'professor',
          departmentId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 5209,
          password: '5209',
          surname: 'Антипова',
          name: 'Любовь',
          patronymic: 'Александровна',
          isMale: false,
          role: 'professor',
          departmentId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 159,
          password: '159',
          surname: 'Вернер',
          name: 'Алексей',
          patronymic: 'Леонидович',
          isMale: true,
          role: 'professor',
          departmentId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 7607,
          password: '7607',
          surname: 'Далевская',
          name: 'Ольга',
          patronymic: 'Петровна',
          isMale: false,
          role: 'professor',
          departmentId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 4789,
          password: '4789',
          surname: 'Маслова',
          name: 'Юлия',
          patronymic: 'Валерьевна',
          isMale: false,
          role: 'professor',
          departmentId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 1266,
          password: '1266',
          surname: 'Нежинский',
          name: 'Владимир',
          patronymic: 'Михайлович',
          isMale: true,
          role: 'professor',
          departmentId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 5205,
          password: '5205',
          surname: 'Нестеренок',
          name: 'Вадим',
          patronymic: 'Владимирович',
          isMale: true,
          role: 'professor',
          departmentId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 11067,
          password: '11067',
          surname: 'Петров',
          name: 'Максим',
          patronymic: 'Викторович',
          isMale: true,
          role: 'professor',
          departmentId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 1323,
          password: '1323',
          surname: 'Степанова',
          name: 'Марина',
          patronymic: 'Александровна',
          isMale: false,
          role: 'professor',
          departmentId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 1033,
          password: '1033',
          surname: 'Ходот',
          name: 'Татьяна',
          patronymic: 'Георгиевна',
          isMale: false,
          role: 'professor',
          departmentId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 1273,
          password: '1273',
          surname: 'Аркина',
          name: 'Ксения',
          patronymic: 'Георгиевна',
          isMale: false,
          role: 'professor',
          departmentId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 1405,
          password: '1405',
          surname: 'Будаев',
          name: 'Виктор',
          patronymic: 'Дмитриевич',
          isMale: true,
          role: 'professor',
          departmentId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 11453,
          password: '11453',
          surname: 'Конькина',
          name: 'Вероника',
          patronymic: 'Сергеевна',
          isMale: false,
          role: 'professor',
          departmentId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 1557,
          password: '1557',
          surname: 'Линчук',
          name: 'Лидия',
          patronymic: 'Владимировна',
          isMale: false,
          role: 'professor',
          departmentId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 9464,
          password: '9464',
          surname: 'Лиховодова',
          name: 'Татьяна',
          patronymic: 'Борисовна',
          isMale: false,
          role: 'professor',
          departmentId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 10362,
          password: '10362',
          surname: 'Павлов',
          name: 'Дмитрий',
          patronymic: 'Александрович',
          isMale: true,
          role: 'professor',
          departmentId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 822,
          password: '822',
          surname: 'Рисс',
          name: 'Елена',
          patronymic: 'Артуровна',
          isMale: false,
          role: 'professor',
          departmentId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 841,
          password: '841',
          surname: 'Рукшин',
          name: 'Сергей',
          patronymic: 'Евгеньевич',
          isMale: true,
          role: 'professor',
          departmentId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 4184,
          password: '4184',
          surname: 'Суслина',
          name: 'Мария',
          patronymic: 'Евгеньевна',
          isMale: false,
          role: 'professor',
          departmentId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 11456,
          password: '11456',
          surname: 'Фофанов',
          name: 'Кирилл',
          patronymic: 'Алексеевич',
          isMale: true,
          role: 'professor',
          departmentId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 10078,
          password: '10078',
          surname: 'Широков',
          name: 'Николай',
          patronymic: 'Алексеевич',
          isMale: true,
          role: 'professor',
          departmentId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 2229,
          password: '2229',
          surname: 'Клещева',
          name: 'Ирина',
          patronymic: 'Валерьевна',
          isMale: false,
          role: 'professor',
          departmentId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 11049,
          password: '11049',
          surname: 'Кожокарь',
          name: 'Ольга',
          patronymic: 'Александровна',
          isMale: false,
          role: 'professor',
          departmentId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 499,
          password: '499',
          surname: 'Кочуренко',
          name: 'Надежда',
          patronymic: 'Владимировна',
          isMale: false,
          role: 'professor',
          departmentId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 511,
          password: '511',
          surname: 'Крылов',
          name: 'Валерий',
          patronymic: 'Валентинович',
          isMale: true,
          role: 'professor',
          departmentId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 571,
          password: '571',
          surname: 'Лисимова',
          name: 'Ольга',
          patronymic: 'Анатольевна',
          isMale: false,
          role: 'professor',
          departmentId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 582,
          password: '582',
          surname: 'Лопачев',
          name: 'Владимир',
          patronymic: 'Александрович',
          isMale: true,
          role: 'professor',
          departmentId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 1244,
          password: '1244',
          surname: 'Орлов',
          name: 'Владимир',
          patronymic: 'Викторович',
          isMale: true,
          role: 'professor',
          departmentId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 727,
          password: '727',
          surname: 'Пиотровская',
          name: 'Ксения',
          patronymic: 'Раймондовна',
          isMale: false,
          role: 'professor',
          departmentId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 738,
          password: '738',
          surname: 'Подходова',
          name: 'Наталья',
          patronymic: 'Семеновна',
          isMale: false,
          role: 'professor',
          departmentId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 8873,
          password: '8873',
          surname: 'Пратусевич',
          name: 'Максим',
          patronymic: 'Яковлевич',
          isMale: true,
          role: 'professor',
          departmentId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 858,
          password: '858',
          surname: 'Сазонова',
          name: 'Наталья',
          patronymic: 'Викторовна',
          isMale: false,
          role: 'professor',
          departmentId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 1345,
          password: '1345',
          surname: 'Снегурова',
          name: 'Виктория',
          patronymic: 'Игоревна',
          isMale: false,
          role: 'professor',
          departmentId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 10647,
          password: '10647',
          surname: 'Солдаева',
          name: 'Мария',
          patronymic: 'Владимировна',
          isMale: false,
          role: 'professor',
          departmentId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 945,
          password: '945',
          surname: 'Стефанова',
          name: 'Наталия',
          patronymic: 'Леонидовна',
          isMale: false,
          role: 'professor',
          departmentId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 8648,
          password: '8648',
          surname: 'Тербушева',
          name: 'Екатерина',
          patronymic: 'Александровна',
          isMale: false,
          role: 'professor',
          departmentId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 2206,
          password: '2206',
          surname: 'Шумара',
          name: 'Елена',
          patronymic: 'Викторовна',
          isMale: false,
          role: 'professor',
          departmentId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 7596,
          password: '7596',
          surname: 'Байгузева',
          name: 'Александра',
          patronymic: 'Петровна',
          isMale: false,
          role: 'professor',
          departmentId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 4116,
          password: '4116',
          surname: 'Пальтиель',
          name: 'Лев',
          patronymic: 'Романович',
          isMale: true,
          role: 'professor',
          departmentId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 937,
          password: '937',
          surname: 'Спивак',
          name: 'Веда',
          patronymic: 'Игоревна',
          isMale: false,
          role: 'professor',
          departmentId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 138,
          password: '138',
          surname: 'Васильев',
          name: 'Владимир',
          patronymic: 'Ефимович',
          isMale: false,
          role: 'professor',
          departmentId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 999999,
          password: '999999',
          surname: 'Ерошкина',
          name: 'Ольга',
          patronymic: 'Николаевна',
          isMale: false,
          role: 'professor',
          departmentId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 2795,
          password: '2795',
          surname: 'Лагутина',
          name: 'Анна',
          patronymic: 'Александровна',
          isMale: false,
          role: 'professor',
          departmentId: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 313,
          password: '313',
          surname: 'Жаркой',
          name: 'Александр',
          patronymic: 'Борисович',
          isMale: true,
          role: 'professor',
          departmentId: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 1882,
          password: '1882',
          surname: 'Кудрявцева',
          name: 'Ирина',
          patronymic: 'Андреевна',
          isMale: false,
          role: 'professor',
          departmentId: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 999998,
          password: '999998',
          surname: 'Михайлов',
          name: 'Александр',
          patronymic: 'Борисович',
          isMale: true,
          role: 'professor',
          departmentId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122978,
          password: '122978',
          surname: 'Ахмедова',
          name: 'Людмила',
          patronymic: 'Гаджимурадовна',
          isMale: false,
          role: 'student',
          groupId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122953,
          password: '122953',
          surname: 'Березина',
          name: 'Алина',
          patronymic: 'Александровна',
          isMale: false,
          role: 'student',
          groupId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 113623,
          password: '113623',
          surname: 'Богачёв',
          name: 'Владимир',
          patronymic: 'Александрович',
          isMale: true,
          role: 'student',
          groupId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 125566,
          password: '125566',
          surname: 'Громова',
          name: 'Елизавета',
          patronymic: 'Андреевна',
          isMale: false,
          role: 'student',
          groupId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122941,
          password: '122941',
          surname: 'Карпушина',
          name: 'Марьяна',
          patronymic: 'Дмитриевна',
          isMale: false,
          role: 'student',
          groupId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122954,
          password: '122954',
          surname: 'Курочкина',
          name: 'Полина',
          patronymic: 'Евгеньевна',
          isMale: false,
          role: 'student',
          groupId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122927,
          password: '122927',
          surname: 'Малиновская',
          name: 'Алиса',
          patronymic: 'Витальевна',
          isMale: false,
          role: 'student',
          groupId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122972,
          password: '122972',
          surname: 'Николаева',
          name: 'Лилия',
          patronymic: 'Аркадьевна',
          isMale: false,
          role: 'student',
          groupId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122945,
          password: '122945',
          surname: 'Острийчук',
          name: 'Александр',
          patronymic: 'Александрович',
          isMale: true,
          role: 'student',
          groupId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122990,
          password: '122990',
          surname: 'Светляков',
          name: 'Юрий',
          patronymic: 'Иванович',
          isMale: true,
          role: 'student',
          groupId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122938,
          password: '122938',
          surname: 'Сергеева',
          name: 'Екатерина',
          patronymic: 'Александровна',
          isMale: false,
          role: 'student',
          groupId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 127759,
          password: '127759',
          surname: 'Трескунова',
          name: 'Рахель',
          patronymic: 'Михайловна',
          isMale: false,
          role: 'student',
          groupId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122987,
          password: '122987',
          surname: 'Яковлева',
          name: 'Дарья',
          patronymic: 'Эдуардовна',
          isMale: false,
          role: 'student',
          groupId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122929,
          password: '122929',
          surname: 'Ануфриева',
          name: 'Оксана',
          patronymic: 'Сергеевна',
          isMale: false,
          role: 'student',
          groupId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122947,
          password: '122947',
          surname: 'Боденчук',
          name: 'Екатерина',
          patronymic: 'Владимировна',
          isMale: false,
          role: 'student',
          groupId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122955,
          password: '122955',
          surname: 'Боровкова',
          name: 'Екатерина',
          patronymic: 'Юрьевна',
          isMale: false,
          role: 'student',
          groupId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 125199,
          password: '125199',
          surname: 'Дмитриева',
          name: 'Кристина',
          patronymic: 'Валентиновна',
          isMale: false,
          role: 'student',
          groupId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122940,
          password: '122940',
          surname: 'Землякова',
          name: 'Александра',
          patronymic: 'Алексеевна',
          isMale: false,
          role: 'student',
          groupId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 117795,
          password: '117795',
          surname: 'Зубиетян',
          name: 'Артем',
          patronymic: 'Каренович',
          isMale: true,
          role: 'student',
          groupId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122994,
          password: '122994',
          surname: 'Казымова',
          name: 'Лейла',
          patronymic: 'Натиговна',
          isMale: false,
          role: 'student',
          groupId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122966,
          password: '122966',
          surname: 'Копытова',
          name: 'Ирина',
          patronymic: 'Дмитриевна',
          isMale: false,
          role: 'student',
          groupId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122952,
          password: '122952',
          surname: 'Лапалайнен',
          name: 'Маргарита',
          patronymic: 'Романовна',
          isMale: false,
          role: 'student',
          groupId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 126288,
          password: '126288',
          surname: 'Новицкая',
          name: 'Валерия',
          patronymic: 'Александровна',
          isMale: false,
          role: 'student',
          groupId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122971,
          password: '122971',
          surname: 'Нужная',
          name: 'Дарья',
          patronymic: 'Дмитриевна',
          isMale: false,
          role: 'student',
          groupId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122974,
          password: '122974',
          surname: 'Рудых',
          name: 'Анастасия',
          patronymic: 'Андреевна',
          isMale: false,
          role: 'student',
          groupId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122983,
          password: '122983',
          surname: 'Смирнова',
          name: 'Дарья',
          patronymic: 'Романовна',
          isMale: false,
          role: 'student',
          groupId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122982,
          password: '122982',
          surname: 'Халапова',
          name: 'Сабина',
          patronymic: 'Эмильевна',
          isMale: false,
          role: 'student',
          groupId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122946,
          password: '122946',
          surname: 'Ятченко',
          name: 'Анна',
          patronymic: 'Сергеевна',
          isMale: false,
          role: 'student',
          groupId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122948,
          password: '122948',
          surname: 'Амосёнок',
          name: 'Анастасия',
          patronymic: 'Дмитриевна',
          isMale: false,
          role: 'student',
          groupId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122958,
          password: '122958',
          surname: 'Андреева',
          name: 'Мария',
          patronymic: 'Андреевна',
          isMale: false,
          role: 'student',
          groupId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122993,
          password: '122993',
          surname: 'Воронина',
          name: 'Полина',
          patronymic: 'Олеговна',
          isMale: false,
          role: 'student',
          groupId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122936,
          password: '122936',
          surname: 'Евграфова',
          name: 'Анастасия',
          patronymic: 'Андреевна',
          isMale: false,
          role: 'student',
          groupId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122968,
          password: '122968',
          surname: 'Зайцева',
          name: 'Елизавета',
          patronymic: 'Алексеевна',
          isMale: false,
          role: 'student',
          groupId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122984,
          password: '122984',
          surname: 'Захарова',
          name: 'Ангелина',
          isMale: false,
          role: 'student',
          groupId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122957,
          password: '122957',
          surname: 'Йазыджы',
          name: 'София',
          patronymic: 'Алиевна',
          isMale: false,
          role: 'student',
          groupId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 123730,
          password: '123730',
          surname: 'Калугина',
          name: 'Ольга',
          patronymic: 'Сергеевна',
          isMale: false,
          role: 'student',
          groupId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122944,
          password: '122944',
          surname: 'Карсакова',
          name: 'Дарья',
          patronymic: 'Олеговна',
          isMale: false,
          role: 'student',
          groupId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122988,
          password: '122988',
          surname: 'Конарева',
          name: 'Наталья',
          patronymic: 'Владимировна',
          isMale: false,
          role: 'student',
          groupId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122939,
          password: '122939',
          surname: 'Корехова',
          name: 'Дина',
          patronymic: 'Алексеевна',
          isMale: false,
          role: 'student',
          groupId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122934,
          password: '122934',
          surname: 'Кузьменкова',
          name: 'Елизавета',
          patronymic: 'Игоревна',
          isMale: false,
          role: 'student',
          groupId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 126388,
          password: '126388',
          surname: 'Оразова',
          name: 'Мяхриджемал',
          isMale: false,
          role: 'student',
          groupId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122979,
          password: '122979',
          surname: 'Саламатина',
          name: 'Юлия',
          patronymic: 'Алексеевна',
          isMale: false,
          role: 'student',
          groupId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 132867,
          password: '132867',
          surname: 'Самойлова',
          name: 'Людмила',
          patronymic: 'Дмитриевна',
          isMale: false,
          role: 'student',
          groupId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122960,
          password: '122960',
          surname: 'Сердюк',
          name: 'Олеся',
          patronymic: 'Эльнуровна',
          isMale: false,
          role: 'student',
          groupId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122951,
          password: '122951',
          surname: 'Соколова',
          name: 'Анастасия',
          patronymic: 'Денисовна',
          isMale: false,
          role: 'student',
          groupId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 125269,
          password: '125269',
          surname: 'Тулумбасова',
          name: 'Маргарита',
          patronymic: 'Михайловна',
          isMale: false,
          role: 'student',
          groupId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122963,
          password: '122963',
          surname: 'Чуксина',
          name: 'Дарья',
          patronymic: 'Андреевна',
          isMale: false,
          role: 'student',
          groupId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 122980,
          password: '122980',
          surname: 'Шкляева',
          name: 'Мария',
          patronymic: 'Викторовна',
          isMale: false,
          role: 'student',
          groupId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {},
    );
  },
};
