module.exports = {
  async up(queryInterface) {
    await queryInterface.bulkInsert(
      'Users',
      [
        {
          login: 11065,
          password: '11065',
          surname: 'Гнутов',
          name: 'Федор',
          patronymic: 'Александрович',
          isMale: true,
          role: 'professor',
          department_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 223,
          password: '223',
          surname: 'Гордеев',
          name: 'Николай',
          patronymic: 'Леонидович',
          isMale: true,
          role: 'professor',
          department_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 9552,
          password: '9552',
          surname: 'Егорченкова',
          name: 'Елизавета',
          patronymic: 'Алексеевна',
          isMale: false,
          role: 'professor',
          department_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 2122,
          password: '2122',
          surname: 'Кушпель',
          name: 'Надежда',
          patronymic: 'Николаевна',
          isMale: false,
          role: 'professor',
          department_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 3629,
          password: '3629',
          surname: 'Певзнер',
          name: 'Игорь',
          patronymic: 'Михайлович',
          isMale: true,
          role: 'professor',
          department_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 1029,
          password: '1029',
          surname: 'Хамов',
          name: 'Геннадий',
          patronymic: 'Григорьевич',
          isMale: true,
          role: 'professor',
          department_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 1127,
          password: '1127',
          surname: 'Яшина',
          name: 'Елена',
          patronymic: 'Юрьевна',
          isMale: false,
          role: 'professor',
          department_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 5209,
          password: '5209',
          surname: 'Антипова',
          name: 'Любовь',
          patronymic: 'Александровна',
          isMale: false,
          role: 'professor',
          department_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 159,
          password: '159',
          surname: 'Вернер',
          name: 'Алексей',
          patronymic: 'Леонидович',
          isMale: true,
          role: 'professor',
          department_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 7607,
          password: '7607',
          surname: 'Далевская',
          name: 'Ольга',
          patronymic: 'Петровна',
          isMale: false,
          role: 'professor',
          department_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 4789,
          password: '4789',
          surname: 'Маслова',
          name: 'Юлия',
          patronymic: 'Валерьевна',
          isMale: false,
          role: 'professor',
          department_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 1266,
          password: '1266',
          surname: 'Нежинский',
          name: 'Владимир',
          patronymic: 'Михайлович',
          isMale: true,
          role: 'professor',
          department_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 5205,
          password: '5205',
          surname: 'Нестеренок',
          name: 'Вадим',
          patronymic: 'Владимирович',
          isMale: true,
          role: 'professor',
          department_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 11067,
          password: '11067',
          surname: 'Петров',
          name: 'Максим',
          patronymic: 'Викторович',
          isMale: true,
          role: 'professor',
          department_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 1323,
          password: '1323',
          surname: 'Степанова',
          name: 'Марина',
          patronymic: 'Александровна',
          isMale: false,
          role: 'professor',
          department_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 1033,
          password: '1033',
          surname: 'Ходот',
          name: 'Татьяна',
          patronymic: 'Георгиевна',
          isMale: false,
          role: 'professor',
          department_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 1273,
          password: '1273',
          surname: 'Аркина',
          name: 'Ксения',
          patronymic: 'Георгиевна',
          isMale: false,
          role: 'professor',
          department_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 1405,
          password: '1405',
          surname: 'Будаев',
          name: 'Виктор',
          patronymic: 'Дмитриевич',
          isMale: true,
          role: 'professor',
          department_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 11453,
          password: '11453',
          surname: 'Конькина',
          name: 'Вероника',
          patronymic: 'Сергеевна',
          isMale: false,
          role: 'professor',
          department_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 1557,
          password: '1557',
          surname: 'Линчук',
          name: 'Лидия',
          patronymic: 'Владимировна',
          isMale: false,
          role: 'professor',
          department_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 9464,
          password: '9464',
          surname: 'Лиховодова',
          name: 'Татьяна',
          patronymic: 'Борисовна',
          isMale: false,
          role: 'professor',
          department_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 10362,
          password: '10362',
          surname: 'Павлов',
          name: 'Дмитрий',
          patronymic: 'Александрович',
          isMale: true,
          role: 'professor',
          department_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 822,
          password: '822',
          surname: 'Рисс',
          name: 'Елена',
          patronymic: 'Артуровна',
          isMale: false,
          role: 'professor',
          department_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 841,
          password: '841',
          surname: 'Рукшин',
          name: 'Сергей',
          patronymic: 'Евгеньевич',
          isMale: true,
          role: 'professor',
          department_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 4184,
          password: '4184',
          surname: 'Суслина',
          name: 'Мария',
          patronymic: 'Евгеньевна',
          isMale: false,
          role: 'professor',
          department_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 11456,
          password: '11456',
          surname: 'Фофанов',
          name: 'Кирилл',
          patronymic: 'Алексеевич',
          isMale: true,
          role: 'professor',
          department_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 10078,
          password: '10078',
          surname: 'Широков',
          name: 'Николай',
          patronymic: 'Алексеевич',
          isMale: true,
          role: 'professor',
          department_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 2229,
          password: '2229',
          surname: 'Клещева',
          name: 'Ирина',
          patronymic: 'Валерьевна',
          isMale: false,
          role: 'professor',
          department_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 11049,
          password: '11049',
          surname: 'Кожокарь',
          name: 'Ольга',
          patronymic: 'Александровна',
          isMale: false,
          role: 'professor',
          department_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 499,
          password: '499',
          surname: 'Кочуренко',
          name: 'Надежда',
          patronymic: 'Владимировна',
          isMale: false,
          role: 'professor',
          department_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 511,
          password: '511',
          surname: 'Крылов',
          name: 'Валерий',
          patronymic: 'Валентинович',
          isMale: true,
          role: 'professor',
          department_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 571,
          password: '571',
          surname: 'Лисимова',
          name: 'Ольга',
          patronymic: 'Анатольевна',
          isMale: false,
          role: 'professor',
          department_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 582,
          password: '582',
          surname: 'Лопачев',
          name: 'Владимир',
          patronymic: 'Александрович',
          isMale: true,
          role: 'professor',
          department_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 1244,
          password: '1244',
          surname: 'Орлов',
          name: 'Владимир',
          patronymic: 'Викторович',
          isMale: true,
          role: 'professor',
          department_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 727,
          password: '727',
          surname: 'Пиотровская',
          name: 'Ксения',
          patronymic: 'Раймондовна',
          isMale: false,
          role: 'professor',
          department_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 738,
          password: '738',
          surname: 'Подходова',
          name: 'Наталья',
          patronymic: 'Семеновна',
          isMale: false,
          role: 'professor',
          department_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 8873,
          password: '8873',
          surname: 'Пратусевич',
          name: 'Максим',
          patronymic: 'Яковлевич',
          isMale: true,
          role: 'professor',
          department_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 858,
          password: '858',
          surname: 'Сазонова',
          name: 'Наталья',
          patronymic: 'Викторовна',
          isMale: false,
          role: 'professor',
          department_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 1345,
          password: '1345',
          surname: 'Снегурова',
          name: 'Виктория',
          patronymic: 'Игоревна',
          isMale: false,
          role: 'professor',
          department_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 10647,
          password: '10647',
          surname: 'Солдаева',
          name: 'Мария',
          patronymic: 'Владимировна',
          isMale: false,
          role: 'professor',
          department_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 945,
          password: '945',
          surname: 'Стефанова',
          name: 'Наталия',
          patronymic: 'Леонидовна',
          isMale: false,
          role: 'professor',
          department_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 8648,
          password: '8648',
          surname: 'Тербушева',
          name: 'Екатерина',
          patronymic: 'Александровна',
          isMale: false,
          role: 'professor',
          department_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          login: 2206,
          password: '2206',
          surname: 'Шумара',
          name: 'Елена',
          patronymic: 'Викторовна',
          isMale: false,
          role: 'professor',
          department_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {},
    );
  },
};
