'use strict';

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Marks',
      [
        {
          student_id: 1,
          grade: 1,
          professor_id: 2,
          date: new Date(2022, 12, 21),
          discipline_id: 1,
          markType: 'зачёт',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          student_id: 1,
          grade: 5,
          professor_id: 3,
          date: new Date(2022, 12, 22),
          discipline_id: 2,
          markType: 'дифф. зачёт',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          student_id: 1,
          grade: 5,
          professor_id: 2,
          date: new Date(2022, 12, 20),
          discipline_id: 3,
          markType: 'дифф. зачёт',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          student_id: 1,
          grade: 5,
          professor_id: 2,
          date: new Date(2022, 12, 26),
          discipline_id: 4,
          markType: 'дифф. зачёт',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          student_id: 1,
          grade: 5,
          professor_id: 4,
          date: new Date(2022, 12, 23),
          discipline_id: 5,
          markType: 'дифф. зачёт',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          student_id: 1,
          grade: 4,
          professor_id: 5,
          date: new Date(2023, 1, 14),
          discipline_id: 6,
          markType: 'экзамен',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          student_id: 1,
          grade: 4,
          professor_id: 6,
          date: new Date(2023, 1, 13),
          discipline_id: 7,
          markType: 'экзамен',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          student_id: 1,
          grade: 4,
          professor_id: 7,
          date: new Date(2023, 1, 14),
          discipline_id: 8,
          markType: 'экзамен',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {},
    );
  },

  async down(queryInterface, Sequelize) {},
};
